spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2s

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.web.error.include-stacktrace=never

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-expiration=PT15M
security.jwt.refresh-token-expiration=720h
